//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Playtb
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTRoom
    {
        public int rid { get; set; }
        public string room_id { get; set; }
        public string url { get; set; }
    }
}
